const doctorTranslations = [
  { email: 'sarah.j@medicai.com', bio_ar: 'طبيبة قلب معتمدة متخصصة في الوقاية من أمراض القلب وعلاج ارتفاع ضغط الدم.', hospital_ar: 'مركز المدينة للقلب' },
  { email: 'michael.c@medicai.com', bio_ar: 'خبير في اضطرابات الجهاز العصبي والصداع النصفي وعلاج الصرع.', hospital_ar: 'معهد العناية بالأعصاب' },
  { email: 'emily.r@medicai.com', bio_ar: 'طبيبة أطفال مخصصة لصحة الطفل والتطعيمات.', hospital_ar: 'المركز الطبي للأطفال' },
  { email: 'james.w@medicai.com', bio_ar: 'جراح عظام متخصص في إصابات الرياضة واستبدال المفاصل.', hospital_ar: 'عيادة العظام والمفاصل' },
  { email: 'lisa.p@medicai.com', bio_ar: 'طبيبة جلدية متخصصة في حب الشباب والأكزيما والجلدية التجميلية.', hospital_ar: 'عيادة صحة الجلد' },
  { email: 'robert.a@medicai.com', bio_ar: 'طبيب طب عائلي ذو خبرة واسعة في رعاية جميع الأعمار.', hospital_ar: 'مستشفى صحة المجتمع' },
  { email: 'anna.k@medicai.com', bio_ar: 'طبيبة نفسية متخصصة في القلق والاكتئاب واضطرابات التوتر.', hospital_ar: 'مركز العافية النفسية' },
  { email: 'david.t@medicai.com', bio_ar: 'أخصائي جهاز هضمي يعالج القولون العصبي والارتجاع المعدي وأمراض الكبد.', hospital_ar: 'معهد صحة الجهاز الهضمي' },
  { email: 'fatima.h@medicai.com', bio_ar: 'أخصائية أورام تركز على الكشف المبكر وخطط علاج السرطان الشخصية.', hospital_ar: 'مركز رعاية السرطان' },
  { email: 'thomas.w@medicai.com', bio_ar: 'أخصائي غدد صماء يعالج السكري واضطرابات الغدة الدرقية والهرمونات.', hospital_ar: 'عيادة صحة الهرمونات' },
  { email: 'priya.s@medicai.com', bio_ar: 'أخصائية أمراض رئة متخصصة في الربو ومرض الانسداد الرئوي وانقطاع النفس أثناء النوم.', hospital_ar: 'مركز الرئة والجهاز التنفسي' },
  { email: 'carlos.m@medicai.com', bio_ar: 'أخصائي مسالك بولية خبير في حصوات الكلى وصحة المسالك البولية.', hospital_ar: 'مركز المسالك البولية' },
  { email: 'yuki.t@medicai.com', bio_ar: 'طبيب قلب تدخلي متخصص في اضطرابات نظم القلب وفشل القلب.', hospital_ar: 'مستشفى مترو للقلب' },
  { email: 'helen.o@medicai.com', bio_ar: 'طبيبة أطفال مهتمة برعاية حديثي الولادة وتغذية الأطفال.', hospital_ar: 'مستشفى شروق الأطفال' },
  { email: 'mark.s@medicai.com', bio_ar: 'أخصائي طب رياضي يعالج الرياضيين والبالغين النشطين.', hospital_ar: 'مركز الطب الرياضي' },
  { email: 'nora.i@medicai.com', bio_ar: 'طبيبة جلدية خبيرة في الصدفية والوردية وفحص حساسية الجلد.', hospital_ar: 'معهد البشرة الصافية' },
  { email: 'kevin.b@medicai.com', bio_ar: 'طبيب نفسي يعالج اضطراب ما بعد الصدمة والوسواس القهري واضطرابات المزاج.', hospital_ar: 'شركاء الصحة السلوكية' },
  { email: 'sophie.l@medicai.com', bio_ar: 'طبيبة جهاز هضمي تركز على مرض الاضطرابات الهضمية وداء كرون والتغذية.', hospital_ar: 'عيادة باريس للجهاز الهضمي' },
  { email: 'omar.k@medicai.com', bio_ar: 'طبيب عائلي كبير بعقود من الخبرة في الرعاية الصحية المجتمعية.', hospital_ar: 'المركز الطبي النور' },
  { email: 'rachel.g@medicai.com', bio_ar: 'طبيبة أعصاب متخصصة في التعافي من السكتة الدماغية ومرض باركنسون.', hospital_ar: 'مركز الدماغ والعمود الفقري' },
];

const questions = [
  {
    patient: 'john.s@example.com',
    title: 'Persistent headache for 3 days',
    title_ar: 'صداع مستمر منذ 3 أيام',
    body: 'I have had a throbbing headache on the right side for 3 days. Painkillers help briefly. Should I be concerned?',
    body_ar: 'أعاني من صداع نابض في الجانب الأيمن منذ 3 أيام. مسكنات الألم تساعد لفترة قصيرة. هل يجب أن أقلق؟',
    category: 'Neurology',
    answers: [
      { user: 'michael.c@medicai.com', body: 'Persistent unilateral headaches lasting more than 72 hours warrant evaluation. Please see a neurologist. Stay hydrated and avoid known triggers.', body_ar: 'الصداع الأحادي الجانب المستمر لأكثر من 72 ساعة يستدعي التقييم الطبي. يرجى مراجعة طبيب أعصاب. حافظ على الترطيب وتجنب المحفزات المعروفة.' },
      { user: 'maria.g@example.com', body: 'I had something similar last year — turned out to be dehydration and screen strain. Try resting in a dark room and drinking more water.', body_ar: 'عانيت من شيء مشابه العام الماضي — تبين أنه بسبب الجفاف وإجهاد العين. جربي الراحة في غرفة مظلمة واشربي المزيد من الماء.' },
    ],
  },
  {
    patient: 'maria.g@example.com',
    title: 'Chest tightness after exercise',
    title_ar: 'ضيق في الصدر بعد التمرين',
    body: 'Sometimes after jogging I feel tightness in my chest for a few minutes. I am 28 and otherwise healthy. Is this normal?',
    body_ar: 'أحياناً بعد الجري أشعر بضيق في صدري لبضع دقائق. عمري 28 وبصحة جيدة. هل هذا طبيعي؟',
    category: 'Cardiology',
    answers: [
      { user: 'sarah.j@medicai.com', body: 'Exercise-induced chest tightness should not be ignored. I recommend an ECG and stress test to rule out cardiac causes. Stop intense exercise until evaluated.', body_ar: 'ضيق الصدر الناتج عن التمرين لا يجب تجاهله. أنصح بإجراء تخطيط قلب واختبار جهد لاستبعاد الأسباب القلبية. توقفي عن التمارين الشاقة حتى التقييم.' },
    ],
  },
  {
    patient: 'ahmed.h@example.com',
    title: 'Child has fever for 2 days',
    title_ar: 'طفل لديه حمى منذ يومين',
    body: 'My 4-year-old has a fever of 38.5°C for two days, is fussy but drinking fluids. When should I take him to the ER?',
    body_ar: 'ابني البالغ 4 سنوات لديه حرارة 38.5°م منذ يومين، متقلب المزاج لكنه يشرب السوائل. متى يجب أن آخذه للطوارئ؟',
    category: 'Pediatrics',
    answers: [
      { user: 'emily.r@medicai.com', body: 'Seek immediate care if fever exceeds 40°C, the child is lethargic, has difficulty breathing, or shows a rash. Otherwise, monitor closely and use age-appropriate fever reducers.', body_ar: 'اطلب رعاية فورية إذا تجاوزت الحرارة 40°م، أو كان الطفل خاملًا، أو يعاني صعوبة في التنفس، أو ظهرت لديه طفح جلدي. وإلا راقبه عن كثب واستخدم خافضات حرارة مناسبة لعمره.' },
      { user: 'helen.o@medicai.com', body: 'At this age, 2 days of moderate fever with good fluid intake is often viral. Watch for ear pulling or sore throat signs. Call if fever lasts beyond 3 days.', body_ar: 'في هذا العمر، حمى معتدلة ليومين مع شرب جيد للسوائل غالباً تكون فيروسية. راقب سحب الأذن أو التهاب الحلق. اتصل بالطبيب إذا استمرت الحمى أكثر من 3 أيام.' },
    ],
  },
  {
    patient: 'sarah.l@example.com',
    title: 'Knee pain after running',
    title_ar: 'ألم في الركبة بعد الجري',
    body: 'I started running 3 weeks ago and now have pain below my kneecap, especially going downstairs. Should I rest or see a doctor?',
    body_ar: 'بدأت الجري منذ 3 أسابيع والآن أشعر بألم أسفل الرضفة، خاصة عند النزول من الدرج. هل أرتاح أم أراجع طبيباً؟',
    category: 'Orthopedics',
    answers: [
      { user: 'james.w@medicai.com', body: "This sounds like patellofemoral pain syndrome (runner's knee). Rest, ice, and strengthen your quads. If pain persists beyond 2 weeks, come in for evaluation.", body_ar: 'يبدو هذا متلازمة ألم الرضفة الفخذية (ركبة العداء). ارتحي، ضعي ثلجاً، وقوّي عضلات الفخذ. إذا استمر الألم أكثر من أسبوعين، احجزي موعداً للتقييم.' },
      { user: 'mark.s@medicai.com', body: 'Reduce mileage by 50% and avoid downhill running. Consider a gait analysis — improper form is a common cause in new runners.', body_ar: 'قللي المسافة بنسبة 50% وتجنبي الجري في المنحدرات. فكري في تحليل المشية — الوضعية الخاطئة سبب شائع لدى المبتدئين.' },
    ],
  },
  {
    patient: 'david.b@example.com',
    title: 'Red itchy rash on arms',
    title_ar: 'طفح أحمر مثير للحكة على الذراعين',
    body: 'Developed a red, itchy rash on both forearms after using a new laundry detergent. Antihistamine helps a little. Could this be an allergy?',
    body_ar: 'ظهر طفح أحمر مثير للحكة على كلتا الساعدين بعد استخدام منظف غسيل جديد. مضاد الهيستامين يساعد قليلاً. هل قد تكون حساسية؟',
    category: 'Dermatology',
    answers: [
      { user: 'lisa.p@medicai.com', body: 'Yes, contact dermatitis from detergent is very common. Switch to fragrance-free detergent, use moisturizer, and a topical steroid cream if needed.', body_ar: 'نعم، التهاب الجلد التماسي من المنظف شائع جداً. انتقل لمنظف خالٍ من العطور، استخدم مرطباً، وكريم ستيرويد موضعي عند الحاجة.' },
      { user: 'nora.i@medicai.com', body: 'Stop using the new detergent immediately. Cool compresses can soothe itching. See a dermatologist if it spreads or blisters form.', body_ar: 'توقف فوراً عن استخدام المنظف الجديد. الكمادات الباردة تخفف الحكة. راجع طبيب جلدية إذا انتشر الطفح أو ظهرت بثور.' },
    ],
  },
  {
    patient: 'fatima.a@example.com',
    title: 'Constant worry and trouble sleeping',
    title_ar: 'قلق مستمر وصعوبة في النوم',
    body: 'For the past month I have been unable to sleep well and worry about everything. I feel tired all day. Is this anxiety?',
    body_ar: 'منذ شهر لا أستطيع النوم جيداً وأقلق من كل شيء. أشعر بالتعب طوال اليوم. هل هذا قلق؟',
    category: 'Psychiatry',
    answers: [
      { user: 'anna.k@medicai.com', body: 'Your symptoms are consistent with generalized anxiety disorder. Cognitive behavioral therapy and lifestyle changes help. We can discuss medication if symptoms are severe.', body_ar: 'أعراضك متوافقة مع اضطراب القلق العام. العلاج السلوكي المعرفي وتغيير نمط الحياة يساعدان. يمكننا مناقشة الدواء إذا كانت الأعراض شديدة.' },
      { user: 'kevin.b@medicai.com', body: 'Sleep disruption and persistent worry are hallmark anxiety signs. Try a sleep routine: no screens 1 hour before bed, consistent wake time, and limit caffeine.', body_ar: 'اضطراب النوم والقلق المستمر من علامات القلق الأساسية. جربي روتين نوم: لا شاشات قبل ساعة من النوم، وقت استيقاظ ثابت، وتقليل الكافيين.' },
    ],
  },
  {
    patient: 'john.s@example.com',
    title: 'Acid reflux every night',
    title_ar: 'حرقة معدة كل ليلة',
    body: 'I get burning in my chest and throat almost every night after dinner. Omeprazole helped for a week then stopped working. What should I do?',
    body_ar: 'أشعر بحرقة في صدري وحلقي تقريباً كل ليلة بعد العشاء. أوميبرازول ساعد لأسبوع ثم توقف عن العمل. ماذا أفعل؟',
    category: 'Gastroenterology',
    answers: [
      { user: 'david.t@medicai.com', body: 'Refractory GERD needs evaluation — possible H. pylori or hiatal hernia. Avoid late meals, elevate your head while sleeping, and we may need endoscopy.', body_ar: 'الارتجاع المعدي المري esophي المقاوم يحتاج تقييماً — قد يكون بكتيريا هيليكوباكتر أو فتق حجابي. تجنب الوجبات المتأخرة، ارفع رأسك أثناء النوم، وقد نحتاج منظاراً.' },
      { user: 'sophie.l@medicai.com', body: 'Try eating dinner 3 hours before bed and avoid spicy/acidic foods. If PPIs stopped working, you may need a dose adjustment — see a GI specialist.', body_ar: 'جرب تناول العشاء قبل 3 ساعات من النوم وتجنب الأطعمة الحارة والحامضة. إذا توقفت مثبطات المضخة عن العمل، قد تحتاج تعديل الجرعة — راجع أخصائي جهاز هضمي.' },
    ],
  },
  {
    patient: 'maria.g@example.com',
    title: 'Always tired despite sleeping 8 hours',
    title_ar: 'تعب دائم رغم النوم 8 ساعات',
    body: 'I sleep 8 hours but wake up exhausted. My partner says I snore loudly. Could this be a sleep problem?',
    body_ar: 'أنام 8 ساعات لكن أستيقظ منهكة. شريكي يقول إنني أشخر بصوت عالٍ. هل قد تكون مشكلة نوم؟',
    category: 'Pulmonology',
    answers: [
      { user: 'priya.s@medicai.com', body: 'Loud snoring with daytime fatigue strongly suggests sleep apnea. A sleep study is recommended. This is treatable with CPAP or lifestyle changes.', body_ar: 'الشخير العالي مع التعب النهاري يشير بقوة لانقطاع النفس أثناء النوم. يُنصح بدراسة النوم. يمكن علاجه بجهاز CPAP أو تغيير نمط الحياة.' },
    ],
  },
  {
    patient: 'ahmed.h@example.com',
    title: 'Blood sugar readings are high',
    title_ar: 'قراءات سكر الدم مرتفعة',
    body: 'My fasting blood sugar has been 140-160 mg/dL for the past week. I was diagnosed with prediabetes last year. Do I need medication now?',
    body_ar: 'سكر الدم الصائم كان 140-160 مجم/دل طوال الأسبوع الماضي. تشخصت بما قبل السكري العام الماضي. هل أحتاج دواء الآن؟',
    category: 'Endocrinology',
    answers: [
      { user: 'thomas.w@medicai.com', body: 'Fasting glucose consistently above 126 mg/dL meets diabetes criteria. You likely need medication plus diet modification. Schedule an HbA1c test promptly.', body_ar: 'جلوكوز الصيام فوق 126 مجم/دل باستمرار يلبي معايير السكري. غالباً تحتاج دواء مع تعديل النظام الغذائي. احجز فحص HbA1c فوراً.' },
      { user: 'robert.a@medicai.com', body: 'These readings are concerning. Cut refined carbs, walk 30 minutes daily, and see an endocrinologist soon for a full diabetes workup.', body_ar: 'هذه القراءات مقلقة. قلل الكربوهيدرات المكررة، امشِ 30 دقيقة يومياً، وراجع أخصائي غدد صماء قريباً لفحص سكري شامل.' },
    ],
  },
  {
    patient: 'sarah.l@example.com',
    title: 'Found a lump in breast',
    title_ar: 'وجدت كتلة في الثدي',
    body: 'I found a small hard lump in my left breast during self-exam. No pain. I am 31. How urgent is this?',
    body_ar: 'وجدت كتلة صغيرة صلبة في ثديي الأيسر أثناء الفحص الذاتي. لا ألم. عمري 31. ما مدى الإلحاح؟',
    category: 'Oncology',
    answers: [
      { user: 'fatima.h@medicai.com', body: 'Any new breast lump requires prompt evaluation regardless of age. Schedule a clinical exam and imaging within 1-2 weeks. Most lumps are benign but must be checked.', body_ar: 'أي كتلة جديدة في الثدي تتطلب تقييماً سريعاً بغض النظر عن العمر. احجزي فحصاً سريرياً وتصويراً خلال 1-2 أسبوع. معظم الكتل حميدة لكن يجب فحصها.' },
    ],
  },
  {
    patient: 'david.b@example.com',
    title: 'Frequent urination at night',
    title_ar: 'كثرة التبول ليلاً',
    body: 'I wake up 3-4 times nightly to urinate. I am a 55-year-old man. Could this be prostate related?',
    body_ar: 'أستيقظ 3-4 مرات ليلاً للتبول. عمري 55 سنة. هل قد يكون مرتبطاً بالبروستاتا؟',
    category: 'Urology',
    answers: [
      { user: 'carlos.m@medicai.com', body: 'Nocturia in men over 50 is often due to benign prostatic hyperplasia. A PSA test and prostate exam are recommended. Limit fluids 2 hours before bed.', body_ar: 'كثرة التبول ليلاً لدى الرجال فوق 50 غالباً بسبب تضخم البروستاتا الحميد. يُنصح بفحص PSA وفحص البروستاتا. قلل السوائل قبل ساعتين من النوم.' },
    ],
  },
  {
    patient: 'fatima.a@example.com',
    title: 'Dry cough for 3 weeks',
    title_ar: 'سعال جاف منذ 3 أسابيع',
    body: 'I have had a dry cough for 3 weeks with no fever. It is worse at night. COVID test was negative. What else could cause this?',
    body_ar: 'لدي سعال جاف منذ 3 أسابيع بدون حمى. يزداد ليلاً. فحص كوفيد سلبي. ما الأسباب الأخرى المحتملة؟',
    category: 'General Medicine',
    answers: [
      { user: 'robert.a@medicai.com', body: 'Post-viral cough, allergies, and acid reflux are common causes. Try honey for cough relief and an air humidifier. If it persists beyond 4 weeks, get a chest X-ray.', body_ar: 'السعال بعد العدوى الفيروسية والحساسية والارتجاع أسباب شائعة. جربي العسل لتهدئة السعال ومرطب هواء. إذا استمر أكثر من 4 أسابيع، أجري أشعة صدر.' },
      { user: 'omar.k@medicai.com', body: 'A 3-week dry cough needs investigation. Check for asthma, reflux, or post-nasal drip. Avoid smoking and irritants. Follow up if not improving.', body_ar: 'سعال جاف لمدة 3 أسابيع يحتاج فحصاً. تحقق من الربو والارتجاع وانسكاب الأنف الخلفي. تجنبي التدخين والمهيجات. تابعي إذا لم يتحسن.' },
    ],
  },
  {
    patient: 'john.s@example.com',
    title: 'Dizzy spells when standing up',
    title_ar: 'دوخة عند الوقوف',
    body: 'Lately I feel dizzy when I stand up quickly. It lasts a few seconds. My blood pressure at home is 110/70. Should I worry?',
    body_ar: 'مؤخراً أشعر بدوخة عند الوقوف بسرعة. تدوم ثوانٍ. ضغطي 110/70. هل يجب أن أقلق؟',
    category: 'Cardiology',
    answers: [
      { user: 'yuki.t@medicai.com', body: 'Orthostatic dizziness can indicate blood pressure drops on standing. Have your BP checked lying and standing. Stay hydrated and rise slowly from sitting.', body_ar: 'الدوخة الانتصابية قد تشير لانخفاض الضغط عند الوقوف. افحص ضغطك مستلقياً وواقفاً. حافظ على الترطيب وانهض ببطء.' },
      { user: 'ahmed.h@example.com', body: 'I experienced this too — increasing water and salt intake helped. Also check if any medications could be causing it.', body_ar: 'عانيت من هذا أيضاً — زيادة الماء والملح ساعدتني. تحقق أيضاً إن كان أي دواء يسبب ذلك.' },
    ],
  },
  {
    patient: 'maria.g@example.com',
    title: 'Severe menstrual cramps',
    title_ar: 'تشنجات دورية شديدة',
    body: 'Every month I have debilitating cramps that keep me in bed for 2 days. Ibuprofen barely helps. Is this endometriosis?',
    body_ar: 'كل شهر أعاني تشنجات شديدة تبقيني في السرير يومين. الإيبوبروفين بالكاد يساعد. هل هذا بطانة رحم مهاجرة؟',
    category: 'General Medicine',
    answers: [
      { user: 'robert.a@medicai.com', body: 'Severe dysmenorrhea affecting daily life needs gynecological evaluation. Endometriosis is possible. Hormonal therapy or further imaging may be needed.', body_ar: 'عسر الطمث الشديد المؤثر على الحياة اليومية يحتاج تقييماً نسائياً. البطانة المهاجرة محتملة. قد نحتاج علاجاً هرمونياً أو تصويراً إضافياً.' },
    ],
  },
  {
    patient: 'ahmed.h@example.com',
    title: 'Tingling in fingers and toes',
    title_ar: 'وخز في الأصابع والقدمين',
    body: 'For the past week I have tingling in my fingertips and toes, especially at night. I have type 2 diabetes. Is this neuropathy?',
    body_ar: 'منذ أسبوع أشعر بوخز في أطراف أصابع اليدين والقدمين، خاصة ليلاً. لدي سكري نوع 2. هل هذا اعتلال أعصاب؟',
    category: 'Neurology',
    answers: [
      { user: 'rachel.g@medicai.com', body: 'Peripheral neuropathy is common in diabetes. Tight blood sugar control is essential. We may prescribe gabapentin for symptom relief and check B12 levels.', body_ar: 'اعتلال الأعصاب الطرفي شائع في السكري. ضبط السكر ضروري. قد نصف جابابنتين لتخفيف الأعراض ونفحص فيتامين B12.' },
      { user: 'thomas.w@medicai.com', body: 'Diabetic neuropathy is likely given your history. Optimize glucose control and have a comprehensive foot exam. Early treatment prevents progression.', body_ar: 'اعتلال الأعصاب السكري محتمل نظراً لتاريخك. حسّن ضبط الجلوكوز وأجرِ فحص قدم شامل. العلاج المبكر يمنع التقدم.' },
    ],
  },
  {
    patient: 'sarah.l@example.com',
    title: 'Eczema flare on hands',
    title_ar: 'تهيج إكزيما على اليدين',
    body: 'My hand eczema has flared badly — cracked, bleeding skin. Regular moisturizer is not helping. What stronger treatment exists?',
    body_ar: 'إكزيما يدي تهيجت بشدة — جلد متشقق ونازف. المرطب العادي لا يساعد. ما العلاج الأقوى المتاح؟',
    category: 'Dermatology',
    answers: [
      { user: 'nora.i@medicai.com', body: 'Severe hand eczema may need prescription topical steroids and barrier creams. Avoid harsh soaps and wear cotton gloves after applying ointment at night.', body_ar: 'إكزيما اليد الشديدة قد تحتاج ستيرويدات موضعية بوصفة وكريمات حاجزة. تجنبي الصابون القاسي وارتدي قفازات قطنية بعد المرهم ليلاً.' },
    ],
  },
  {
    patient: 'david.b@example.com',
    title: 'Lower back pain radiating to leg',
    title_ar: 'ألم أسفل الظهر يمتد للساق',
    body: 'Lower back pain for 2 weeks now shoots down my right leg. Sitting makes it worse. Could this be a slipped disc?',
    body_ar: 'ألم أسفل الظهر منذ أسبوعين يمتد لساقي اليمنى. الجلوس يزيده. هل قد يكون انزلاق غضروفي؟',
    category: 'Orthopedics',
    answers: [
      { user: 'james.w@medicai.com', body: 'Sciatica from disc herniation is likely. Most cases improve with physical therapy in 6-8 weeks. Seek urgent care if you lose bladder control or leg strength.', body_ar: 'عرق النسا من انزلاق غضروفي محتمل. معظم الحالات تتحسن بالعلاج الطبيعي خلال 6-8 أسابيع. اطلب رعاية عاجلة إذا فقدت التحكم بالمثانة أو قوة الساق.' },
    ],
  },
  {
    patient: 'fatima.a@example.com',
    title: 'Loss of appetite and weight loss',
    title_ar: 'فقدان الشهية ونقص الوزن',
    body: 'I have lost 5 kg in 6 weeks without trying. I have no appetite and feel nauseous. What tests should I get?',
    body_ar: 'فقدت 5 كجم في 6 أسابيع دون محاولة. لا شهية لدي وأشعر بالغثيان. ما الفحوصات التي أحتاجها؟',
    category: 'Gastroenterology',
    answers: [
      { user: 'sophie.l@medicai.com', body: 'Unintentional weight loss needs thorough workup — blood tests, thyroid panel, and possibly endoscopy. Do not delay; schedule an appointment this week.', body_ar: 'فقدان الوزن غير المقصود يحتاج فحصاً شاملاً — تحاليل دم، غدة درقية، وربما منظار. لا تؤجلي؛ احجزي موعداً هذا الأسبوع.' },
      { user: 'fatima.h@medicai.com', body: 'Significant unexplained weight loss requires urgent evaluation to rule out serious conditions. Complete blood count and metabolic panel are first steps.', body_ar: 'فقدان وزن كبير غير مبرر يتطلب تقييماً عاجلاً لاستبعاد حالات خطيرة. تعداد دم شامل ولوحة أيضية هي الخطوات الأولى.' },
    ],
  },
  {
    patient: 'john.s@example.com',
    title: 'Can I take aspirin daily for heart health?',
    title_ar: 'هل يمكنني تناول الأسبرين يومياً لصحة القلب؟',
    body: 'I am 42 with no heart problems. I read daily aspirin prevents heart attacks. Is it safe to start on my own?',
    body_ar: 'عمري 42 ولا مشاكل قلبية. قرأت أن الأسبرين اليومي يمنع النوبات. هل آمن أن أبدأ بمفردي؟',
    category: 'Cardiology',
    answers: [
      { user: 'sarah.j@medicai.com', body: 'Daily aspirin is NOT recommended for primary prevention in low-risk adults under 60. It increases bleeding risk. Focus on diet, exercise, and blood pressure control instead.', body_ar: 'الأسبرين اليومي غير موصى به للوقاية الأولية لدى البالغين منخفضي الخطورة دون 60. يزيد خطر النزيف. ركز على النظام الغذائي والرياضة وضبط الضغط بدلاً من ذلك.' },
    ],
  },
  {
    patient: 'ahmed.h@example.com',
    title: 'Best diet for high cholesterol?',
    title_ar: 'أفضل نظام غذائي لارتفاع الكوليسترول؟',
    body: 'My LDL is 165 mg/dL. Doctor said change diet before medication. What foods should I eat and avoid?',
    body_ar: 'LDL لدي 165 مجم/دل. الطبيب قال غيّر النظام الغذائي قبل الدواء. ما الأطعمة التي آكلها وأتجنبها؟',
    category: 'General Medicine',
    answers: [
      { user: 'omar.k@medicai.com', body: 'Reduce saturated fats (red meat, full-fat dairy), increase soluble fiber (oats, beans, apples), and add omega-3s from fish. Exercise 150 min/week. Recheck lipids in 3 months.', body_ar: 'قلل الدهون المشبعة (لحم أحمر، ألبان كاملة الدسم)، زد الألياف القابلة للذوبان (شوفان، فاصوليا، تفاح)، وأضف أوميغا 3 من السمك. تمارين 150 دقيقة أسبوعياً. أعد فحص الدهون بعد 3 أشهر.' },
      { user: 'david.b@example.com', body: 'I lowered mine with oatmeal breakfasts, grilled chicken instead of fried food, and walnuts as snacks. It really works if you stick with it!', body_ar: 'خفضت نسبتي بفطور الشوفان، دجاج مشوي بدل المقلي، والجوز كوجبة خفيفة. يفعل مع الالتزام!' },
    ],
  },
];

module.exports = { doctorTranslations, questions };
